<?php
$title = 'Delete News';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($news->title); ?>' by
    '<?php echo $this->escapeHtml($news->date); ?>'?
</p>
<?php
$url = $this->url('news', array(
    'action' => 'delete',
    'id'     => $this->news_id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="news_id" value="<?php echo (int) $news->news_id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>