<?php
$title = 'Edit News';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'news',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('news_id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('theme_id'));
echo $this->formRow($form->get('date'));
echo $this->formRow($form->get('text'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();